info: # add this section
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    git:
      mode: full

spring:
  application:
    name: cloud-native-spring